### ISSUE TITLE
Project doesn't seem to build with Maven

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege-ontology-server#2]
```
[INFO] --- exec-maven-plugin:1.2.1:exec (generate-users-and-groups-parser) @ org.protege.owl.server ---
warning(24):  template error: context [outputFile parser genericParser region__genericParser__members] 32:3 no such property or can't access: org.antlr.tool.Grammar.indirectDelegates
Caused by: org.stringtemplate.v4.misc.STNoSuchPropertyException: no such property: org.antlr.tool.Grammar.indirectDelegates
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.throwNoSuchProperty(ObjectModelAdaptor.java:110)
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.lookupMethod(ObjectModelAdaptor.java:103)
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.getProperty(ObjectModelAdaptor.java:71)
	at org.stringtemplate.v4.Interpreter.getObjectProperty(Interpreter.java:1115)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:208)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:143)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:691)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:623)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:283)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:143)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:691)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:623)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:283)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:143)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:691)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:623)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:283)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:143)
	at org.stringtemplate.v4.ST.write(ST.java:365)
	at org.antlr.codegen.CodeGenerator.write(CodeGenerator.java:1296)
	at org.antlr.codegen.Target.genRecognizerFile(Target.java:98)
	at org.antlr.codegen.CodeGenerator.genRecognizer(CodeGenerator.java:459)
	at org.antlr.Tool.generateRecognizer(Tool.java:696)
	at org.antlr.Tool.process(Tool.java:509)
	at org.antlr.Tool.main(Tool.java:98)

[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (generate-policy-parser) @ org.protege.owl.server ---
warning(24):  template error: context [outputFile parser genericParser region__genericParser__members] 32:3 no such property or can't access: org.antlr.tool.Grammar.indirectDelegates
Caused by: org.stringtemplate.v4.misc.STNoSuchPropertyException: no such property: org.antlr.tool.Grammar.indirectDelegates
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.throwNoSuchProperty(ObjectModelAdaptor.java:110)
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.lookupMethod(ObjectModelAdaptor.java:103)
	at org.stringtemplate.v4.misc.ObjectModelAdaptor.getProperty(ObjectModelAdaptor.java:71)
	at org.stringtemplate.v4.Interpreter.getObjectProperty(Interpreter.java:1115)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:208)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:143)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:691)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:623)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:283)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:143)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:691)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:623)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:283)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:143)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:691)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:623)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:283)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:143)
	at org.stringtemplate.v4.ST.write(ST.java:365)
	at org.antlr.codegen.CodeGenerator.write(CodeGenerator.java:1296)
	at org.antlr.codegen.Target.genRecognizerFile(Target.java:98)
	at org.antlr.codegen.CodeGenerator.genRecognizer(CodeGenerator.java:459)
	at org.antlr.Tool.generateRecognizer(Tool.java:696)
	at org.antlr.Tool.process(Tool.java:509)
	at org.antlr.Tool.main(Tool.java:98)

[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ org.protege.owl.server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ org.protege.owl.server ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 138 source files to /Users/matthewhorridge/IdeaProjects/org.protege.owl.server/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /Users/matthewhorridge/IdeaProjects/org.protege.owl.server/src/main/java/org/protege/owl/server/changes/ChangeHistoryImpl.java: Some input files use or override a deprecated API.
[WARNING] /Users/matthewhorridge/IdeaProjects/org.protege.owl.server/src/main/java/org/protege/owl/server/changes/ChangeHistoryImpl.java: Recompile with -Xlint:deprecation for details.
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/matthewhorridge/IdeaProjects/org.protege.owl.server/src/main/java/org/protege/owl/server/connect/local/OSGiLocalTransport.java:[11,32] type org.osgi.framework.ServiceRegistration does not take parameters
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.099 s
[INFO] Finished at: 2015-05-01T14:28:23-07:00
[INFO] Final Memory: 18M/221M
[INFO] ------------------------------------------------------------------------
```

**Comment by rsgoncalves** [comment]
Fixed by dfeea22838ea3e451c0d34a5ae4a98abb3e4d076
